<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vdmldi" nsURI="http://www.omg.org/spec/VDML/20131201/DI" nsPrefix="vdmldi">
  <eClassifiers xsi:type="ecore:EClass" name="VDMLDiagram" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//Diagram #//VDMLDiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedVdmlDiagramElement"
        upperBound="-1" eType="#//VDMLDiagramElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VDMLEdge" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//Edge #//VDMLDiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceShape" eType="#//VDMLShape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetShape" eType="#//VDMLShape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VDMLShape" eSuperTypes="../../jbpm-designer-extensions-emf/models/jBPMDD.ecore#//BoundariedShape #//VDMLDiagramElement ../../jbpm-designer-extensions-emf/models/jBPMDD.ecore#//CollapsibleShape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedShape" upperBound="-1"
        eType="#//VDMLShape" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VDMLDiagramElement" abstract="true"
      interface="true" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vdmlElement" eType="ecore:EClass VDML.ecore#//VdmlElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VDMLStyle" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//Style"/>
</ecore:EPackage>
