<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cmmndi" nsURI="http://www.omg.org/spec/CMMN/20131201/DI" nsPrefix="cmmndi">
  <eClassifiers xsi:type="ecore:EClass" name="CMMNDiagram" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//Diagram #//CMMNDiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCmmnDiagramElement"
        upperBound="-1" eType="#//CMMNDiagramElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCmmnStyles" upperBound="-1"
        eType="#//CMMNStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmmnElement" eType="ecore:EClass CMMN.ecore#//TDefinitions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMMNEdge" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//Edge #//CMMNDiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceShape" eType="#//CMMNShape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetShape" eType="#//CMMNShape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmmnElement" eType="ecore:EClass CMMN.ecore#//TCmmnElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMMNShape" eSuperTypes="../../jbpm-designer-extensions-emf/models/jBPMDD.ecore#//BoundariedShape #//CMMNDiagramElement ../../jbpm-designer-extensions-emf/models/jBPMDD.ecore#//CollapsibleShape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedShape" upperBound="-1"
        eType="#//CMMNShape" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPlanningTableExpanded"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmmnElement" eType="ecore:EClass CMMN.ecore#//TCmmnElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMMNDiagramElement" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CMMNStyle" eSuperTypes="../../jbpm-designer-extensions-emf/models/DI.ecore#//Style"/>
</ecore:EPackage>
